create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_records (account_id bigint not null, records_id bigint not null) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table accounts_records add constraint UK_q62pgjlvqfdnfdh2enn8l5hix unique (records_id);
alter table accounts_records add constraint FK68fscjrenkddx87jl55i6k59w foreign key (records_id) references records (id);
alter table accounts_records add constraint FK8qp1anof7tmuf73egej8lougv foreign key (account_id) references accounts (id);
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_records (account_id bigint not null, records_id bigint not null) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table accounts_records add constraint UK_q62pgjlvqfdnfdh2enn8l5hix unique (records_id);
alter table accounts_records add constraint FK68fscjrenkddx87jl55i6k59w foreign key (records_id) references records (id);
alter table accounts_records add constraint FK8qp1anof7tmuf73egej8lougv foreign key (account_id) references accounts (id);
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_records (account_id bigint not null, records_id bigint not null) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table accounts_records add constraint UK_q62pgjlvqfdnfdh2enn8l5hix unique (records_id);
alter table accounts_records add constraint FK68fscjrenkddx87jl55i6k59w foreign key (records_id) references records (id);
alter table accounts_records add constraint FK8qp1anof7tmuf73egej8lougv foreign key (account_id) references accounts (id);
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_records (account_id bigint not null, records_id bigint not null) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table accounts_records add constraint UK_q62pgjlvqfdnfdh2enn8l5hix unique (records_id);
alter table accounts_records add constraint FK68fscjrenkddx87jl55i6k59w foreign key (records_id) references records (id);
alter table accounts_records add constraint FK8qp1anof7tmuf73egej8lougv foreign key (account_id) references accounts (id);
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_records (account_id bigint not null, records_id bigint not null) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table accounts_records add constraint UK_q62pgjlvqfdnfdh2enn8l5hix unique (records_id);
alter table accounts_records add constraint FK68fscjrenkddx87jl55i6k59w foreign key (records_id) references records (id);
alter table accounts_records add constraint FK8qp1anof7tmuf73egej8lougv foreign key (account_id) references accounts (id);
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_records (account_id bigint not null, records_id bigint not null) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table accounts_records add constraint UK_q62pgjlvqfdnfdh2enn8l5hix unique (records_id);
alter table accounts_records add constraint FK68fscjrenkddx87jl55i6k59w foreign key (records_id) references records (id);
alter table accounts_records add constraint FK8qp1anof7tmuf73egej8lougv foreign key (account_id) references accounts (id);
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_records (account_id bigint not null, records_id bigint not null) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table accounts_records add constraint UK_q62pgjlvqfdnfdh2enn8l5hix unique (records_id);
alter table accounts_records add constraint FK68fscjrenkddx87jl55i6k59w foreign key (records_id) references records (id);
alter table accounts_records add constraint FK8qp1anof7tmuf73egej8lougv foreign key (account_id) references accounts (id);
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_records (account_id bigint not null, records_id bigint not null) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table accounts_records add constraint UK_q62pgjlvqfdnfdh2enn8l5hix unique (records_id);
alter table accounts_records add constraint FK68fscjrenkddx87jl55i6k59w foreign key (records_id) references records (id);
alter table accounts_records add constraint FK8qp1anof7tmuf73egej8lougv foreign key (account_id) references accounts (id);
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
create table users (id bigint not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
create table users (id bigint not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
create table users (id bigint not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
create table accounts (id bigint not null, balance bigint, color varchar(255), currency varchar(255), icon varchar(255), include_in_statistic bit, name varchar(255), primary key (id)) engine=InnoDB;
create table accounts_seq (next_val bigint) engine=InnoDB;
insert into accounts_seq values ( 1 );
create table categories (id bigint not null, icon varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table categories_seq (next_val bigint) engine=InnoDB;
insert into categories_seq values ( 1 );
create table records (id bigint not null, amount bigint, created datetime(6), label varchar(255), note varchar(255), account_id bigint, category_id bigint, primary key (id)) engine=InnoDB;
create table records_seq (next_val bigint) engine=InnoDB;
insert into records_seq values ( 1 );
create table users (id bigint not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table records add constraint FKebsyfevo8atf8joyq6wli8b9k foreign key (account_id) references accounts (id);
alter table records add constraint FKoup71yrh5btbl78kidsoqoyfj foreign key (category_id) references categories (id);
