server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: user
    password: user_password
    name: moneybag-local
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create
  sql:
    init:
      mode: never
#      mode: always
